<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.1.4</Version>
    <AssemblyName>Jellyfin.Plugin.AutoLut</AssemblyName>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <DebugType>none</DebugType>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Jellyfin.Controller" Version="12.1.0" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Jellyfin.Model" Version="12.1.0" ExcludeAssets="runtime" PrivateAssets="all" />
    <Compile Remove="tests/**" />
    <EmbeddedResource Include="Configuration.html" />
    <EmbeddedResource Include="WebPlayer.js" />
  </ItemGroup>
</Project>
